# Site wide configuration

title: Sina Valizadeh
locale: en_US
description: English Teacher (IELTS & TOEFL)
logo: site-logo.png
search: true
#url: http://localhost:4000
url: http://sinavalizade.ir/


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Sina Valizade
  avatar: bio-photo.jpg
  email: sina.s.valizade@gmail.com
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  github: sinaval
  stackexchange: #username
  linkedin: pooyagolchian
  instagram: sinavalizade.ir
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  behence: #
  telegram: valizade_sina
  google:
    plus: #username
    analytics: UA-114457345-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
